language: node_js
node_js:
- lts/*
script:
- npm ci
- npm test
- npm run build
deploy:
  provider: npm
  email: matt@mattcook.xyz
  api_key:
    secure: fh/IbUQP7qztQxoSmFYggHSoJS7/8JM7Q2oNB6JSlWMNOWVNxrzxUHoRusCAxoSKNH8oJu7Xcpvj94JhOkrsFvzaX/JEFWI3uxmtfII1y1xQI56UBtwT0U+gKKo4w5fZIuaRm1TdSGyur4m8B5gzNiP/yCziITGFKCJyULG0JNPyoNaxIZqvjcMwsyj4/9UAk/163YpZyk65mJPkBCDXZcZGcgkSRT8X+6Ev0djwu/VAVSWLeHeHweL3zEJe3cIypjsMtP0YliEjhtLIsNvNwdets+I7rk1SPxOEeY7xeCKW4dJSguvrIzSVLo1oKqnpkPiTgKU7lVjdZSRQ2xTL/8iCEmtUPMNwS1oopDRAP67GyQ8q8y7Crb2UV6vx/9kfod+JWHkMSIVcInXyoc6NB07k19Jxj6cP9VIWgd5SSx7ZnEcnN6dRbiMGg+WwmWxH4rN8uEhxSPiL2vTdAiNJZ9wQQWsC8ta3hx4FbW/2mCIJE6GTDifYJ/0lChBmIvTG68AoNZEIUjTb4kkQL5Tal32e1D+Du3J1qXaqyKST7UQcUudv5YGa6zEh2JgnMNHuFOJGvUU87DZ+IVhsqCYErFXAT5BGUf08skhuekDF0uI4UxI/M+v964xFDLX5XMMnOP7mJ4ls3f0kgguYk8RWUVFZjPauydSK0PPh5U8zWbU=
  on:
    tags: true
    repo: mattcookxyz/music-theory-toolkit