language: node_js
node_js:
- lts/*
script:
- npm ci
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: matt@mattcook.xyz
  on:
    tags: true
  api_key:
    secure: U/CBxN3J4d+2F+0ufHQIqDcTNFUnLBjvvcF4KcRcugdrLkQ8Yw6V0xjbifVF3xGxARDxUkrfZvD5vVWg4t+p9oQVd7Lqje2y0Gblk3rjfzH4eoYETNgtUNXFOrX4L9t6PldfQ3xUy3aZWZjrba0CsFnfKTSsaGZ6vM17iu6dL7hDa9n+/1GOkpgKj+66DpIQrJMw6NLK4KE86yiwRQSjEPCrAAPCGV7cwbPDwo+KiaulnadvOgB70+XiTDpQohVo3K8Qqplu9EZLz7NPLbF81axrhTJo96Detu1arwg2JjP1MoJgNm0GBm9tfABe2lYLFpwN+4jsVEnlEik4PGfRbwS8Zdfgie9KXXfUbWWjUBSHOYuec4tNnY7Q0T9W6IApaQy8U/EDYJAG8KqfFEJkDlH3A91N9sFd4eRuA40X1O07e8JckNUnuFA4G5pQ1jp4gTsKZgZ1zBgJmWYfoxbP45ZZqB8rbtRhw3qaHIsw+hj28UgaBwTHpLFIHXh6tc3VkAxvXEgXzVgjtGFvh1C25mjBPCoC8xaZ/7Ijn0c5UEaJ8/MZlV9ZoL4kGLQbi+YahOEI2yfqoeq9idqqdS4JWamlWiFamFlYmrEjrjBaQyGXvV0SdINolU5InjUYDY6IJLiZmTb9RyaIQX7dTrbvzji6SLCjVFxnfjkrgmkcbN8=
