name: Test

on:
  push:
    branches:
      - dev/*
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      - run: npm run build
      - run: npm pack
